"""Kotlin AST analysis using tree-sitter-kotlin.

Walks the tree-sitter parse tree to extract function and method declarations
that overlap with the changed line set in a diff.

Notes on the tree-sitter-kotlin grammar (verified against tree-sitter-kotlin
0.3.x):
- ``package_header`` contains a ``qualified_identifier`` whose children
  are ``identifier`` nodes separated by ``.``.
- ``class_declaration``, ``object_declaration`` have a child ``identifier``
  (the name) and a child ``class_body`` (the brace-enclosed members). They
  do NOT use ``child_by_field_name``.
- ``companion_object`` has no name child — it represents ``companion
  object { ... }``. We synthesise the name "Companion" (which is Kotlin's
  default name for an unnamed companion).
- ``function_declaration`` has a child ``identifier`` (the name) and a
  body that's either a ``function_body`` block or an expression body.

Skipped: generated files (Apollo, kapt, etc.) — detected via header
comment markers.
"""

from __future__ import annotations

from functools import lru_cache

from pr_test_automator_local.models import AffectedFunction
from pr_test_automator_local.utils.exceptions import CodeAnalyzerError

# Strong markers — these alone are sufficient to mark a file as generated.
_STRONG_GENERATED_MARKERS = (
    "GENERATED CODE",
    "This file was automatically generated",
    "@javax.annotation.Generated",
    "@javax.annotation.processing.Generated",
    "// Generated by Apollo",
    "// AUTO-GENERATED",
)


@lru_cache(maxsize=1)
def _get_parser():
    """Lazily import tree-sitter-kotlin and construct a parser.

    Cached because parser construction is non-trivial and we want to reuse
    it across the whole pipeline.

    Raises CodeAnalyzerError with an actionable install hint if the
    optional dependencies aren't installed.
    """
    try:
        import tree_sitter_kotlin as tsk
        from tree_sitter import Language, Parser
    except ImportError as exc:
        raise CodeAnalyzerError(
            "Kotlin parsing requires the 'tree-sitter' and "
            "'tree-sitter-kotlin' packages. Install them with:\n"
            "  pip install tree-sitter tree-sitter-kotlin\n"
            f"Underlying error: {exc}"
        ) from exc

    language = Language(tsk.language())
    return Parser(language)


def is_generated(source_code: str) -> bool:
    """True if the file appears to be tool-generated and should be skipped."""
    head = source_code[:4096]
    return any(marker in head for marker in _STRONG_GENERATED_MARKERS)


def extract_affected(
    source_code: str,
    file_path: str,
    changed_lines: set[int],
) -> list[AffectedFunction]:
    """Return functions/methods overlapping ``changed_lines``.

    Includes:
    - Top-level functions
    - Methods inside class, object, interface declarations
    - Methods inside companion objects (qualified as ``Outer.Companion.x``)
    - Methods inside nested classes (qualified through the chain)
    - Secondary constructors (named after the enclosing class)
    """
    if is_generated(source_code):
        return []

    parser = _get_parser()
    source_bytes = source_code.encode("utf-8")

    try:
        tree = parser.parse(source_bytes)
    except Exception as exc:
        raise CodeAnalyzerError(
            f"Kotlin parse failed in {file_path}: {exc}"
        ) from exc

    source_lines = source_code.splitlines()
    package_name = _extract_package(tree.root_node, source_bytes)
    results: list[AffectedFunction] = []

    _walk(
        tree.root_node,
        source_bytes,
        source_lines,
        changed_lines,
        file_path,
        package_name,
        class_stack=[],
        results=results,
    )

    return results


# ---------------------------------------------------------------------------
# Walker
# ---------------------------------------------------------------------------


def _walk(
    node,
    source_bytes: bytes,
    source_lines: list[str],
    changed_lines: set[int],
    file_path: str,
    package_name: str,
    class_stack: list[str],
    results: list[AffectedFunction],
) -> None:
    """Recursive walker. Tracks the chain of enclosing classes so methods
    get qualified names like ``com.foo.Outer.Inner.myMethod``.

    The grammar nests members inside ``class_body`` nodes. We recurse into:
    - ``source_file`` (root) -> walk children
    - ``class_declaration``/``object_declaration`` -> find class_body child,
      push name onto stack, recurse into class_body, pop
    - ``companion_object`` -> push "Companion", recurse into its class_body
    - ``class_body`` -> walk children
    - ``function_declaration`` -> emit if it overlaps changed_lines
    - ``secondary_constructor`` -> emit as constructor kind

    Any other node type: recurse into children. This catches cases where
    the grammar embeds declarations inside wrapper nodes we don't know
    about.
    """
    for child in node.children:
        ntype = child.type

        if ntype == "class_declaration":
            name = _first_identifier_text(child, source_bytes)
            if name is None:
                _walk(child, source_bytes, source_lines, changed_lines,
                      file_path, package_name, class_stack, results)
                continue
            class_stack.append(name)
            _walk(child, source_bytes, source_lines, changed_lines,
                  file_path, package_name, class_stack, results)
            class_stack.pop()

        elif ntype == "object_declaration":
            name = _first_identifier_text(child, source_bytes)
            if name is None:
                _walk(child, source_bytes, source_lines, changed_lines,
                      file_path, package_name, class_stack, results)
                continue
            class_stack.append(name)
            _walk(child, source_bytes, source_lines, changed_lines,
                  file_path, package_name, class_stack, results)
            class_stack.pop()

        elif ntype == "companion_object":
            # Companion objects are unnamed by default — Kotlin gives them
            # the name "Companion". (You CAN name them e.g.
            # ``companion object Factory`` but Asurint doesn't, and we
            # treat the synthetic name as good enough for qualifying.)
            class_stack.append("Companion")
            _walk(child, source_bytes, source_lines, changed_lines,
                  file_path, package_name, class_stack, results)
            class_stack.pop()

        elif ntype == "function_declaration":
            kind = "method" if class_stack else "function"
            _maybe_emit(
                child, source_bytes, source_lines, changed_lines,
                file_path, package_name, class_stack, results, kind,
            )

        elif ntype == "secondary_constructor":
            _maybe_emit(
                child, source_bytes, source_lines, changed_lines,
                file_path, package_name, class_stack, results,
                "constructor",
            )

        else:
            # Recurse for: source_file, class_body, package_header (no-op),
            # any other wrapper nodes. We do NOT track depth — the
            # tree is finite and bounded.
            _walk(child, source_bytes, source_lines, changed_lines,
                  file_path, package_name, class_stack, results)


def _maybe_emit(
    fn_node,
    source_bytes: bytes,
    source_lines: list[str],
    changed_lines: set[int],
    file_path: str,
    package_name: str,
    class_stack: list[str],
    results: list[AffectedFunction],
    kind: str,
) -> None:
    """If the function overlaps changed_lines, emit an AffectedFunction."""
    if kind == "constructor":
        name = class_stack[-1] if class_stack else "<init>"
    else:
        name = _first_identifier_text(fn_node, source_bytes)
        if name is None:
            return

    start_line = fn_node.start_point[0] + 1
    end_line = fn_node.end_point[0] + 1
    snippet_start = _expand_to_include_annotations(source_lines, start_line)

    if not any(snippet_start <= ln <= end_line for ln in changed_lines):
        return

    snippet = "\n".join(source_lines[snippet_start - 1 : end_line])
    qualified = ".".join(
        part for part in (package_name, *class_stack, name) if part
    )

    results.append(
        AffectedFunction(
            file_path=file_path,
            name=name,
            qualified_name=qualified,
            kind=kind,
            source_code=snippet,
            line_start=snippet_start,
            line_end=end_line,
        )
    )


# ---------------------------------------------------------------------------
# Node helpers
# ---------------------------------------------------------------------------


def _first_identifier_text(node, source_bytes: bytes) -> str | None:
    """Return the text of the first ``identifier`` child of node.

    Used to find the name of a class/object/function: the grammar puts the
    name as a direct identifier child, after the keyword.

    Skips identifiers that are inside `modifiers` (those are annotation
    names, not the declaration's name).
    """
    for child in node.children:
        if child.type == "modifiers":
            continue
        if child.type == "identifier":
            return source_bytes[child.start_byte : child.end_byte].decode(
                "utf-8"
            )
    return None


def _extract_package(root, source_bytes: bytes) -> str:
    """Find the ``package foo.bar`` declaration and return its dotted name.

    The grammar nests it as:
        package_header
            package (keyword)
            qualified_identifier
                identifier 'foo'
                . '.'
                identifier 'bar'
    """
    for child in root.children:
        if child.type != "package_header":
            continue
        for sub in child.children:
            if sub.type == "qualified_identifier":
                # Use the raw text — tree-sitter preserves the dots
                return source_bytes[sub.start_byte : sub.end_byte].decode(
                    "utf-8"
                )
            if sub.type == "identifier":
                # Single-segment package name
                return source_bytes[sub.start_byte : sub.end_byte].decode(
                    "utf-8"
                )
    return ""


def _expand_to_include_annotations(
    source_lines: list[str], start_line: int
) -> int:
    """Walk upward from start_line, including any annotation lines
    immediately above (and the blank lines between them, only if at least
    one annotation is found).

    The tree-sitter-kotlin grammar usually nests annotations under
    ``modifiers`` which is inside the function/class node, so this
    expansion is rarely needed. But we keep it symmetric with the Java
    and Python analyzers as a safety net for grammar edge cases.
    """
    line_idx = start_line - 2
    saw_annotation = False

    while line_idx >= 0:
        stripped = source_lines[line_idx].strip()
        if stripped.startswith("@"):
            saw_annotation = True
            line_idx -= 1
            continue
        if stripped == "":
            line_idx -= 1
            continue
        break

    return line_idx + 2 if saw_annotation else start_line


# ---------------------------------------------------------------------------
# collect_annotations — used by Stage 4 to detect Spring annotations etc.
# ---------------------------------------------------------------------------


def collect_annotations(
    source_code: str, file_path: str
) -> dict[str, list[str]]:
    """Return ``{class_name: [annotation_names...]}`` for every class.

    Annotations are pulled from the ``modifiers`` child of each class
    declaration. The text after ``@`` (before any parens) is the name.
    """
    if is_generated(source_code):
        return {}

    parser = _get_parser()
    source_bytes = source_code.encode("utf-8")
    tree = parser.parse(source_bytes)
    result: dict[str, list[str]] = {}

    _collect_recursive(
        tree.root_node, source_bytes, class_stack=[], result=result
    )
    return result


def _collect_recursive(
    node, source_bytes: bytes, class_stack: list[str], result: dict
) -> None:
    for child in node.children:
        if child.type in ("class_declaration", "object_declaration"):
            name = _first_identifier_text(child, source_bytes)
            if name:
                qualified = ".".join([*class_stack, name])
                result[qualified] = _gather_annotations(child, source_bytes)
                class_stack.append(name)
                _collect_recursive(
                    child, source_bytes, class_stack, result
                )
                class_stack.pop()
            else:
                _collect_recursive(
                    child, source_bytes, class_stack, result
                )
        else:
            _collect_recursive(
                child, source_bytes, class_stack, result
            )


def _gather_annotations(node, source_bytes: bytes) -> list[str]:
    """Pull annotation names from the modifiers child of a class/method node."""
    names: list[str] = []
    for child in node.children:
        if child.type != "modifiers":
            continue
        for mod in child.children:
            if mod.type != "annotation":
                continue
            # Annotation node typically contains: '@' followed by user_type
            # or constructor_invocation. Extract the textual name.
            text = source_bytes[mod.start_byte : mod.end_byte].decode(
                "utf-8"
            )
            # Drop the leading '@' and any '(...)' arguments
            cleaned = text.lstrip("@").split("(")[0].strip()
            if cleaned:
                names.append(cleaned)
    return names
