"""Java AST analysis using tree-sitter-java.

Mirror of languages/python/analyzer.py but for Java. Walks the tree-sitter
parse tree and pulls out method declarations (and class declarations for
context) that overlap with the changed line set.

Why tree-sitter over javalang/javaparser? tree-sitter handles partial/broken
input gracefully (real codebases have weird files), is fast enough for 100s
of files, and uses the same grammar IntelliJ-class tools use.

This module also exposes detection for jOOQ-generated source so the
analyzer can skip those files. jOOQ marks generated files with a
recognizable comment near the top of the file.
"""

from __future__ import annotations

from functools import lru_cache

from pr_test_automator_local.models import AffectedFunction
from pr_test_automator_local.utils.exceptions import CodeAnalyzerError

# tree-sitter imports are deferred to _get_parser() so that a missing
# tree-sitter install only blows up if someone actually parses Java
# (not just imports the package). This keeps the Python-only install path
# working without forcing every user to pull in tree-sitter.

_JOOQ_GENERATED_MARKERS = (
    "This file is generated by jOOQ.",
    "@javax.annotation.Generated",
    "@javax.annotation.processing.Generated",
)


@lru_cache(maxsize=1)
def _get_parser():
    """Lazily import tree-sitter and build a Java parser.

    Cached so we only construct the parser once per process. Raises a
    clear error if the optional dependencies aren't installed.
    """
    try:
        import tree_sitter_java as tsj
        from tree_sitter import Language, Parser
    except ImportError as exc:
        raise CodeAnalyzerError(
            "Java parsing requires the 'tree-sitter' and "
            "'tree-sitter-java' packages. Install them with:\n"
            "  pip install tree-sitter tree-sitter-java\n"
            f"Underlying error: {exc}"
        ) from exc

    language = Language(tsj.language())
    return Parser(language)


def is_generated(source_code: str) -> bool:
    """True if the source looks like jOOQ- or annotation-processor-generated
    code we should skip.

    Heuristic: check the first 2KB of the file for known generation markers.
    This catches jOOQ's typical header without scanning the whole file.
    """
    head = source_code[:2048]
    return any(marker in head for marker in _JOOQ_GENERATED_MARKERS)


def extract_affected(
    source_code: str,
    file_path: str,
    changed_lines: set[int],
) -> list[AffectedFunction]:
    """Return the methods/constructors overlapping changed_lines.

    Skips jOOQ-generated source entirely (returns []). For non-generated
    code, walks the tree-sitter parse tree, collects every method and
    constructor declaration, and returns the ones whose line range
    intersects the changed set.

    The returned snippet for each method INCLUDES its annotations and
    modifiers so the LLM has full Spring context (e.g. @Autowired,
    @Transactional, @Override).
    """
    if is_generated(source_code):
        return []

    parser = _get_parser()
    source_bytes = source_code.encode("utf-8")

    try:
        tree = parser.parse(source_bytes)
    except Exception as exc:
        # tree-sitter rarely raises — it tolerates broken input. If it does,
        # surface the file name for debugging.
        raise CodeAnalyzerError(
            f"Java parse failed in {file_path}: {exc}"
        ) from exc

    source_lines = source_code.splitlines()
    package_name = _extract_package(tree.root_node, source_bytes)
    results: list[AffectedFunction] = []

    # Walk class declarations to capture method context (which class owns
    # the method). We need this because Java methods are always inside a
    # class, and the qualified name must include the class.
    for class_node in _walk_classes(tree.root_node):
        class_name = _node_field_text(class_node, "name", source_bytes)
        if class_name is None:
            continue

        for method_node in _walk_methods(class_node):
            method_name = _node_field_text(
                method_node, "name", source_bytes
            )
            if method_name is None:
                # Constructor — use the class name as the method name
                method_name = (
                    class_name
                    if method_node.type == "constructor_declaration"
                    else "<unknown>"
                )

            # tree-sitter rows are 0-indexed; convert to 1-indexed file lines
            start_line = method_node.start_point[0] + 1
            end_line = method_node.end_point[0] + 1

            # Capture the method's full block INCLUDING leading annotations
            # and modifiers. tree-sitter includes them as the first children
            # of the method node when present, so start_point already
            # encompasses them. But for the "snippet", we expand to also
            # include preceding annotation lines that tree-sitter sometimes
            # places at the parent level.
            snippet_start = _expand_to_include_annotations(
                source_lines, start_line
            )

            if not _overlaps(snippet_start, end_line, changed_lines):
                continue

            snippet = "\n".join(
                source_lines[snippet_start - 1 : end_line]
            )

            qualified = (
                f"{package_name}.{class_name}.{method_name}"
                if package_name
                else f"{class_name}.{method_name}"
            )

            kind = (
                "constructor"
                if method_node.type == "constructor_declaration"
                else "method"
            )

            results.append(
                AffectedFunction(
                    file_path=file_path,
                    name=method_name,
                    qualified_name=qualified,
                    kind=kind,
                    source_code=snippet,
                    line_start=snippet_start,
                    line_end=end_line,
                )
            )

    return results


# ---------------------------------------------------------------------------
# Tree walking helpers
# ---------------------------------------------------------------------------


def _walk_classes(root):
    """Yield every class_declaration node (and interface/enum/record)."""
    stack = [root]
    while stack:
        node = stack.pop()
        if node.type in (
            "class_declaration",
            "interface_declaration",
            "enum_declaration",
            "record_declaration",
        ):
            yield node
        # Recurse — Java allows nested classes
        stack.extend(node.children)


def _walk_methods(class_node):
    """Yield every method_declaration / constructor_declaration directly
    contained in this class's body.

    We don't descend into nested classes (anonymous inner classes, etc.) —
    those are surfaced by their own _walk_classes iteration. This avoids
    double-counting and keeps the qualified name accurate to the outer
    class.
    """
    body = class_node.child_by_field_name("body")
    if body is None:
        return
    for child in body.children:
        if child.type in ("method_declaration", "constructor_declaration"):
            yield child


def _extract_package(root, source_bytes: bytes) -> str:
    """Find the 'package com.foo.bar;' declaration if present."""
    for child in root.children:
        if child.type == "package_declaration":
            # The package_declaration node is "package <name>;" — pull the
            # text between the keyword and the semicolon.
            for sub in child.children:
                if sub.type in (
                    "scoped_identifier",
                    "identifier",
                ):
                    return source_bytes[
                        sub.start_byte : sub.end_byte
                    ].decode("utf-8")
    return ""


def _node_field_text(node, field_name: str, source_bytes: bytes) -> str | None:
    """Return the text of node.child_by_field_name(field_name), or None."""
    field = node.child_by_field_name(field_name)
    if field is None:
        return None
    return source_bytes[field.start_byte : field.end_byte].decode("utf-8")


def _overlaps(start: int, end: int, changed_lines: set[int]) -> bool:
    """True if any changed line falls within [start, end] inclusive."""
    return any(start <= ln <= end for ln in changed_lines)


def _expand_to_include_annotations(
    source_lines: list[str], start_line: int
) -> int:
    """Walk upward from start_line, including any annotation lines
    immediately above (and the blank lines between them).

    tree-sitter's method node usually encompasses annotations already
    (they're part of the 'modifiers' child). But just in case the grammar
    splits them off, we sweep upward over annotation lines so the LLM
    sees @Autowired, @Override, @Transactional, etc.

    We only expand past blank lines if we encounter at least one
    annotation — otherwise the snippet would gratuitously include leading
    whitespace from the previous declaration. Stops at the first
    non-annotation, non-blank line.
    """
    line_idx = start_line - 2  # 0-indexed, one above start_line
    saw_annotation = False
    pending_blank_lines: list[int] = []

    while line_idx >= 0:
        stripped = source_lines[line_idx].strip()
        if stripped.startswith("@"):
            saw_annotation = True
            pending_blank_lines.clear()
            line_idx -= 1
            continue
        if stripped == "":
            pending_blank_lines.append(line_idx)
            line_idx -= 1
            continue
        break

    if saw_annotation:
        # Include the annotation lines (line_idx points to the line BELOW
        # the last useful line at this point — annotations + their blanks
        # are above)
        return line_idx + 2
    # No annotations found: start at the method itself, not at the blank
    # lines above it
    return start_line


# ---------------------------------------------------------------------------
# Convenience: enumerate annotations on a method node, for prompt hints later
# ---------------------------------------------------------------------------


def collect_annotations(source_code: str, file_path: str) -> dict[str, list[str]]:
    """Return a dict of class_name -> [annotation_names_on_that_class].

    Not used by extract_affected itself — Stage 4 prompts will use this to
    bias test-style decisions (e.g. detect @Service vs @Controller vs
    @Configuration so the prompt knows which testing pattern to recommend).
    """
    if is_generated(source_code):
        return {}

    parser = _get_parser()
    source_bytes = source_code.encode("utf-8")
    tree = parser.parse(source_bytes)
    result: dict[str, list[str]] = {}

    for class_node in _walk_classes(tree.root_node):
        class_name = _node_field_text(class_node, "name", source_bytes)
        if class_name is None:
            continue
        annotations = _gather_annotations(class_node, source_bytes)
        result[class_name] = annotations
    return result


def _gather_annotations(node, source_bytes: bytes) -> list[str]:
    """Collect annotation names attached to a class/method/field node."""
    names: list[str] = []
    for child in node.children:
        if child.type == "modifiers":
            for mod in child.children:
                if mod.type in ("marker_annotation", "annotation"):
                    name_node = mod.child_by_field_name("name")
                    if name_node is not None:
                        names.append(
                            source_bytes[
                                name_node.start_byte : name_node.end_byte
                            ].decode("utf-8")
                        )
    return names
