"""Step 7: Write tests, optionally commit, push, and open a PR."""

from __future__ import annotations

import os
import shutil
import subprocess

from pr_test_automator_local._logging import get_logger
from pr_test_automator_local.config import LocalTestConfig
from pr_test_automator_local.models import GeneratedTest, PRInfo, TestRunResult
from pr_test_automator_local.utils.exceptions import TestCommitterError

logger = get_logger(__name__)

_GIT_TIMEOUT = 60


class TestCommitter:
    """Writes test files to disk; commits / pushes / opens PR per config flags."""

    def __init__(self, config: LocalTestConfig) -> None:
        self._config = config

    def commit(
        self,
        tests: list[GeneratedTest],
        pr_info: PRInfo,
        test_result: TestRunResult | None,
    ) -> tuple[str | None, str | None]:
        """Write generated tests; conditionally commit based on flags + result.

        Returns (commit_sha, pr_url) — either or both may be None.

        Commit policy:
        - commit_tests=False (default): write only, never commit
        - commit_tests=True:
            - commit_only_if_passing=True (default): commit only when tests pass
            - commit_only_if_passing=False: always commit, even with failures
        """
        written = self._write_files(tests)
        if not written:
            logger.info("no test files to write")
            return None, None

        if not self._config.commit_tests:
            logger.info(
                "wrote test files but commit_tests=False — leaving uncommitted",
                extra={"count": len(written)},
            )
            return None, None

        # Optionally skip the commit when tests didn't pass.
        if (
            self._config.commit_only_if_passing
            and test_result
            and not test_result.is_passing
        ):
            logger.warning(
                "tests did not pass — skipping commit "
                "(use --commit-on-failure to override)",
                extra={
                    "passed": test_result.passed,
                    "failed": test_result.failed,
                    "errors": test_result.errors,
                },
            )
            return None, None

        self._git_add(written)
        commit_sha = self._git_commit(len(written), test_result)

        pr_url: str | None = None
        if self._config.push:
            self._git_push(pr_info.head_branch)
            if self._config.open_pr:
                pr_url = self._open_pr_via_gh(pr_info)

        return commit_sha, pr_url

    def _write_files(self, tests: list[GeneratedTest]) -> list[str]:
        """Write each generated test to its canonical path.

        The content has already been generated by the LLM with the
        canonical class name. No transformation needed at commit time —
        the runner uses a transform when writing the temp file (to add
        the ``_PRBot`` prefix), but the original ``gen.content`` remains
        canonical for the committer.
        """
        written: list[str] = []
        for gen in tests:
            dest = os.path.join(self._config.repo_path, gen.test_file_path)
            os.makedirs(os.path.dirname(dest), exist_ok=True)

            with open(dest, "w", encoding="utf-8") as fh:
                fh.write(gen.content)
            written.append(gen.test_file_path)
            logger.info("wrote test file", extra={"path": gen.test_file_path})
        return written

    def _git_add(self, paths: list[str]) -> None:
        self._run(["git", "add", "--", *paths])

    def _git_commit(
        self, file_count: int, test_result: TestRunResult | None
    ) -> str:
        body_lines = [
            f"Auto-generated by pr-test-automator-local for "
            f"{file_count} file(s).",
        ]
        if test_result:
            body_lines.append("")
            body_lines.append(
                f"Test results: {test_result.passed} passed, "
                f"{test_result.failed} failed, {test_result.errors} errors."
            )
            if test_result.failed_test_ids:
                body_lines.append("Failing tests:")
                for tid in test_result.failed_test_ids[:10]:
                    body_lines.append(f"  - {tid}")
                if len(test_result.failed_test_ids) > 10:
                    extra = len(test_result.failed_test_ids) - 10
                    body_lines.append(f"  ... and {extra} more")

        message = "chore: add auto-generated tests\n\n" + "\n".join(body_lines)

        self._run(
            [
                "git",
                "-c", f"user.name={self._config.bot_name}",
                "-c", f"user.email={self._config.bot_email}",
                "commit",
                "-m", message,
            ]
        )
        return self._run(
            ["git", "rev-parse", "HEAD"], capture=True
        ).strip()

    def _git_push(self, branch: str) -> None:
        """Push the current branch, pulling+rebasing first if remote has new commits.

        If the rebase produces conflicts, we abort cleanly and raise so the
        operator can resolve them manually. We never force-push.
        """
        # 1. Make sure we know about the latest remote state
        try:
            self._run(["git", "fetch", "origin", branch])
        except TestCommitterError:
            # Branch doesn't exist on origin yet — first push, nothing to rebase
            logger.info(
                "remote branch not found — first push for this branch",
                extra={"branch": branch},
            )
            self._run(["git", "push", "origin", f"HEAD:{branch}"])
            return

        # 2. Check whether the remote has commits we don't
        try:
            local_only = self._run(
                ["git", "rev-list", f"origin/{branch}..HEAD", "--count"],
                capture=True,
            ).strip()
            remote_only = self._run(
                ["git", "rev-list", f"HEAD..origin/{branch}", "--count"],
                capture=True,
            ).strip()
        except TestCommitterError as exc:
            logger.warning(
                "could not compare with remote — attempting plain push",
                extra={"error": str(exc)},
            )
            self._run(["git", "push", "origin", f"HEAD:{branch}"])
            return

        logger.info(
            "branch divergence check",
            extra={
                "branch": branch,
                "local_only_commits": local_only,
                "remote_only_commits": remote_only,
            },
        )

        if remote_only != "0":
            # Remote has commits we don't have — rebase before pushing
            logger.info(
                f"remote has {remote_only} commit(s) we don't — rebasing",
                extra={"branch": branch},
            )
            try:
                self._run(["git", "rebase", f"origin/{branch}"])
            except TestCommitterError as exc:
                # Rebase failed — almost certainly conflicts. Abort cleanly.
                logger.error(
                    "rebase produced conflicts — aborting and skipping push. "
                    "Pull manually, resolve conflicts, and re-run the bot.",
                    extra={"branch": branch},
                )
                # Try to leave the working tree in a clean state
                try:
                    self._run(["git", "rebase", "--abort"])
                except TestCommitterError:
                    logger.warning(
                        "git rebase --abort also failed — your working tree "
                        "may be in a partial rebase state. Run "
                        "`git rebase --abort` manually."
                    )
                raise TestCommitterError(
                    f"merge conflicts while rebasing on origin/{branch}. "
                    f"Resolve manually with `git pull --rebase` and re-run. "
                    f"Underlying error: {exc}"
                ) from exc

        # 3. Now safe to push
        self._run(["git", "push", "origin", f"HEAD:{branch}"])

    def _open_pr_via_gh(self, pr_info: PRInfo) -> str | None:
        if not shutil.which("gh"):
            logger.warning(
                "`gh` CLI not found — skipping PR open. "
                "Install GitHub CLI from https://cli.github.com/"
            )
            return None

        # Check if PR already exists for this branch.
        try:
            existing = subprocess.run(
                [
                    "gh", "pr", "view", pr_info.head_branch,
                    "--json", "url",
                    "--jq", ".url",
                ],
                capture_output=True,
                text=True,
                cwd=self._config.repo_path,
                timeout=_GIT_TIMEOUT,
                check=False,
            )
            if existing.returncode == 0 and existing.stdout.strip():
                url = existing.stdout.strip()
                logger.info("PR already exists", extra={"url": url})
                return url
        except subprocess.TimeoutExpired:
            pass

        title = "Auto-generated tests"
        body = (
            "Tests generated locally by pr-test-automator-local.\n\n"
            f"Branch `{pr_info.head_branch}` vs `{pr_info.base_branch}`."
        )
        try:
            proc = subprocess.run(
                [
                    "gh", "pr", "create",
                    "--base", pr_info.base_branch,
                    "--head", pr_info.head_branch,
                    "--title", title,
                    "--body", body,
                ],
                capture_output=True,
                text=True,
                cwd=self._config.repo_path,
                timeout=_GIT_TIMEOUT,
                check=True,
            )
            url = proc.stdout.strip().splitlines()[-1] if proc.stdout else ""
            logger.info("PR created", extra={"url": url})
            return url
        except subprocess.CalledProcessError as exc:
            logger.warning(
                "gh pr create failed", extra={"stderr": exc.stderr.strip()}
            )
            return None

    def _run(self, cmd: list[str], capture: bool = False) -> str:
        try:
            proc = subprocess.run(
                cmd,
                cwd=self._config.repo_path,
                capture_output=capture,
                text=True,
                timeout=_GIT_TIMEOUT,
                check=True,
            )
            return proc.stdout if capture else ""
        except subprocess.CalledProcessError as exc:
            raise TestCommitterError(
                f"command failed: {' '.join(cmd)}\n{exc.stderr}"
            ) from exc
        except subprocess.TimeoutExpired as exc:
            raise TestCommitterError(
                f"command timed out: {' '.join(cmd)}"
            ) from exc